name: Build Windows Binaries

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          #cache: 'pip' # caching pip dependencies

      - name: WORKAROUND UNTIL I HAVE A BETTER SOLUTION
        run: |
          pwd
          ls
          cp -r traininglib_/traininglib ./traininglib
          ls traininglib/datalib.py
      
      - name: Install requirements
        run: |
          ./deno.bat task cache
          pip install -r requirements.frozen.txt
        
      - name: Build
        run: python build.py --zip
      
      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: builds/*.zip
        if-no-files-found: error


  integration_tests:
    needs: build
    runs-on: windows-latest
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: binaries
          path: build/

      - run: |
          ls
          ls build/
          unzip build/*.zip

      - name: Run integration tests
        shell: bash
        run: |
          MAINBAT=$(find ./ -name main.bat)
          if [ -z "$MAINBAT" ]; then
            echo "main.bat not found in artifact" >&2
            exit 1
          fi
          CMD=$MAINBAT ./run_tests_integration.sh



