name: Build Windows Binaries

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        default: false



jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies

      - name: WORKAROUND UNTIL I HAVE A BETTER SOLUTION
        run: |
          pwd
          ls
          cp -r traininglib_/traininglib ./traininglib
          ls traininglib/datalib.py
      
      - name: Install requirements
        run: |
          ./deno.bat task cache
          pip install -r requirements.frozen.txt
        
      - name: Build
        run: python build.py --zip
      
      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: builds/*.zip
          if-no-files-found: error


  integration_tests:
    needs: build
    runs-on: windows-latest
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: binaries
          path: build/

      - name: Unzip
        shell: bash
        run: |
          ls
          ls build/
          #unzip build/*.zip
          for f in build/*.zip; do unzip -o "$f" -d build/extracted/; done

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - run: pip install pytest

      - name: Run integration tests
        shell: bash
        run: |
          MAINBAT=$(find build/extracted -name main.bat)
          if [ -z "$MAINBAT" ]; then
            echo "main.bat not found in artifact" >&2
            exit 1
          fi
          # forward slashes to backward slashes
          MAINBATWINPATH="${MAINBAT//\//\\}"
          CMD="cmd.exe /c ${MAINBATWINPATH}"
          echo "CMD=${CMD}"
          CMD=$CMD ./run_tests_integration.sh

  release:
    if: ${{ github.event.inputs.release == 'true' }}
    needs: integration_tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
          path: build/
      
      - name: Set tag 
        id: set_tag
        run: |
          TAGNAME=v$(date +%F)
          echo $TAGNAME
          echo "TAG=${TAGNAME}" >> $GITHUB_OUTPUT
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.zip"
          prerelease: true
          tag: ${{ steps.set_tag.outputs.TAG }}

